version: "3"

services:
    nginx:
        image: nginx:latest
        restart: always
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - 8080:80
        depends_on:
            - app
        container_name: iitushop_nginx

    app:
        restart: always
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        container_name: iitushop_app
        depends_on:
            - db

    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: iitushop
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8081:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: iitushop_db

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8082:80
        container_name: iitushop_phpmyadmin
